project_id = "hooffptvzsvwukvstjai"

[functions.encrypt-data]
verify_jwt = true

[functions.manage-sensitive-data]
verify_jwt = true

[functions.google-drive]
verify_jwt = true

[functions.google-sheets-sync]
verify_jwt = true

[functions.test-twilio]
verify_jwt = true

[functions.test-gmail]
verify_jwt = true

[functions.hubspot]
verify_jwt = true

[functions.verify-document]
verify_jwt = true

[functions.send-client-invitation]
verify_jwt = true

[functions.send-client-invitation-sms]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.receive-sms]
verify_jwt = false

[functions.receive-call]
verify_jwt = false

[functions.call-status]
verify_jwt = false

[functions.make-call]
verify_jwt = true

[functions.outbound-call-twiml]
verify_jwt = false

[functions.ivr-menu]
verify_jwt = false

[functions.process-workflow]
verify_jwt = false

[functions.send-callback-reminders]
verify_jwt = false
