project_id = "hooffptvzsvwukvstjai"

[functions.google-drive]
verify_jwt = true

[functions.google-sheets-sync]
verify_jwt = true

[functions.hubspot]
verify_jwt = true

[functions.verify-document]
verify_jwt = true

[functions.send-client-invitation]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.receive-sms]
verify_jwt = false

[functions.process-workflow]
verify_jwt = false
